# Generated by Django 4.0 on 2021-12-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('size', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size_eu',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_uk',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_us',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
