# Generated by Django 4.0 on 2021-12-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('size', '0002_alter_size_size_eu_alter_size_size_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size_eu',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_uk',
            field=models.DecimalField(decimal_places=0, max_digits=23),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_us',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
